apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      # VULNERABILIDAD CORREGIDA (MEDIUM): Container Running As Root
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: web
        image: localhost:5000/tablon-web:1.0
        imagePullPolicy: Always
        # VULNERABILIDAD CORREGIDA (HIGH): Privilege Escalation Allowed
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
  - port: 5000
    targetPort: 5000
